<?php

namespace Database\Seeders;

use App\Models\Setup\SetupLga;
use Illuminate\Database\Seeder;

class SetupLgaSeeder extends Seeder
{
    public function run(): void
    {
        $localGovernmentAreas = [

            // ===================== ABIA STATE (state_id = 1, 17 LGA)
            1 => [
                'Aba North',
                'Aba South',
                'Arochukwu',
                'Bende',
                'Ikwuano',
                'Isiala Ngwa North',
                'Isiala Ngwa South',
                'Isuikwuato',
                'Obi Ngwa',
                'Ohafia',
                'Osisioma',
                'Ugwunagbo',
                'Ukwa East',
                'Ukwa West',
                'Umuahia North',
                'Umuahia South',
                'Umu Nneochi',
            ],

            // ===================== ADAMAWA STATE (state_id = 2, 21 LGA)
            2 => [
                'Demsa',
                'Fufore',
                'Ganye',
                'Gayuk',
                'Gombi',
                'Grie',
                'Hong',
                'Jada',
                'Lamurde',
                'Madagali',
                'Maiha',
                'Mayo-Belwa',
                'Michika',
                'Mubi North',
                'Mubi South',
                'Numan',
                'Shelleng',
                'Song',
                'Toungo',
                'Yola North',
                'Yola South',
            ],

            // ===================== AKWA IBOM STATE (state_id = 3, 31 LGA)
            3 => [
                'Abak',
                'Eastern Obolo',
                'Eket',
                'Esit Eket',
                'Essien Udim',
                'Etim Ekpo',
                'Etinan',
                'Ibeno',
                'Ibesikpo Asutan',
                'Ibiono-Ibom',
                'Ika',
                'Ikono',
                'Ikot Abasi',
                'Ikot Ekpene',
                'Ini',
                'Itu',
                'Mbo',
                'Mkpat-Enin',
                'Nsit-Atai',
                'Nsit-Ibom',
                'Nsit-Ubium',
                'Obot Akara',
                'Okobo',
                'Onna',
                'Oron',
                'Oruk Anam',
                'Udung-Uko',
                'Ukanafun',
                'Uruan',
                'Urue-Offong/Oruko',
                'Uyo',
            ],

            // ===================== ANAMBRA STATE (state_id = 4, 21 LGA)
            4 => [
                'Aguata',
                'Anambra East',
                'Anambra West',
                'Anaocha',
                'Awka North',
                'Awka South',
                'Ayamelum',
                'Dunukofia',
                'Ekwusigo',
                'Idemili North',
                'Idemili South',
                'Ihiala',
                'Njikoka',
                'Nnewi North',
                'Nnewi South',
                'Ogbaru',
                'Onitsha North',
                'Onitsha South',
                'Orumba North',
                'Orumba South',
                'Oyi',
            ],

            // ===================== BAUCHI STATE (state_id = 5, 20 LGA)
            5 => [
                'Alkaleri',
                'Bauchi',
                'Bogoro',
                'Damban',
                'Darazo',
                'Dass',
                'Gamawa',
                'Ganjuwa',
                'Giade',
                'Itas/Gadau',
                "Jama'are",
                'Katagum',
                'Kirfi',
                'Misau',
                'Ningi',
                'Shira',
                'Tafawa Balewa',
                'Toro',
                'Warji',
                'Zaki',
            ],

            // ===================== BAYELSA STATE (state_id = 6, 8 LGA)
            6 => [
                'Brass',
                'Ekeremor',
                'Kolokuma/Opokuma',
                'Nembe',
                'Ogbia',
                'Sagbama',
                'Southern Ijaw',
                'Yenagoa',
            ],

            // ===================== BENUE STATE (state_id = 7, 23 LGA)
            7 => [
                'Ado',
                'Agatu',
                'Apa',
                'Buruku',
                'Gboko',
                'Guma',
                'Gwer East',
                'Gwer West',
                'Katsina-Ala',
                'Konshisha',
                'Kwande',
                'Logo',
                'Makurdi',
                'Obi',
                'Ogbadibo',
                'Ohimini',
                'Oju',
                'Okpokwu',
                'Otukpo',
                'Tarka',
                'Ukum',
                'Ushongo',
                'Vandeikya',
            ],

            // ===================== BORNO STATE (state_id = 8, 27 LGA)
            8 => [
                'Abadam',
                'Askira/Uba',
                'Bama',
                'Bayo',
                'Biu',
                'Chibok',
                'Damboa',
                'Dikwa',
                'Gubio',
                'Guzamala',
                'Gwoza',
                'Hawul',
                'Jere',
                'Kaga',
                'Kala/Balge',
                'Konduga',
                'Kukawa',
                'Kwaya Kusar',
                'Mafa',
                'Magumeri',
                'Maiduguri',
                'Marte',
                'Mobbar',
                'Monguno',
                'Ngala',
                'Nganzai',
                'Shani',
            ],

            // ===================== CROSS RIVER STATE (state_id = 9, 18 LGA)
            9 => [
                'Abi',
                'Akamkpa',
                'Akpabuyo',
                'Bakassi',
                'Bekwarra',
                'Biase',
                'Boki',
                'Calabar Municipal',
                'Calabar South',
                'Etung',
                'Ikom',
                'Obanliku',
                'Obubra',
                'Obudu',
                'Odukpani',
                'Ogoja',
                'Yakuur',
                'Yala',
            ],

            // ===================== DELTA STATE (state_id = 10, 25 LGA)
            10 => [
                'Aniocha North',
                'Aniocha South',
                'Bomadi',
                'Burutu',
                'Ethiope East',
                'Ethiope West',
                'Ika North East',
                'Ika South',
                'Isoko North',
                'Isoko South',
                'Ndokwa East',
                'Ndokwa West',
                'Okpe',
                'Oshimili North',
                'Oshimili South',
                'Patani',
                'Sapele',
                'Udu',
                'Ughelli North',
                'Ughelli South',
                'Ukwuani',
                'Uvwie',
                'Warri North',
                'Warri South',
                'Warri South West',
            ],

            // ===================== EBONYI STATE (state_id = 11, 13 LGA)
            11 => [
                'Abakaliki',
                'Afikpo North',
                'Afikpo South',
                'Ebonyi',
                'Ezza North',
                'Ezza South',
                'Ikwo',
                'Ishielu',
                'Ivo',
                'Izzi',
                'Ohaozara',
                'Ohaukwu',
                'Onicha',
            ],

            // ===================== EDO STATE (state_id = 12, 18 LGA)
            12 => [
                'Akoko-Edo',
                'Egor',
                'Esan Central',
                'Esan North-East',
                'Esan South-East',
                'Esan West',
                'Etsako Central',
                'Etsako East',
                'Etsako West',
                'Igueben',
                'Ikpoba-Okha',
                'Oredo',
                'Orhionmwon',
                'Ovia North-East',
                'Ovia South-West',
                'Owan East',
                'Owan West',
                'Uhunmwonde',
            ],

            // ===================== EKITI STATE (state_id = 13, )
            13 => [
                'Ado-Ekiti',
                'Efon',
                'Ekiti East',
                'Ekiti South-West',
                'Ekiti West',
                'Emure',
                'Gbonyin',
                'Ido-Osi',
                'Ijero',
                'Ikere',
                'Ikole',
                'Ilejemeje',
                'Irepodun/Ifelodun',
                'Ise/Orun',
                'Moba',
                'Oye',
            ],

            // ===================== ENUGU STATE (state_id = 14, 17 LGA)
            14 => [
                'Aninri',
                'Awgu',
                'Enugu East',
                'Enugu North',
                'Enugu South',
                'Ezeagu',
                'Igbo Etiti',
                'Igbo Eze North',
                'Igbo Eze South',
                'Isi Uzo',
                'Nkanu East',
                'Nkanu West',
                'Nsukka',
                'Oji River',
                'Udenu',
                'Udi',
                'Uzo-Uwani',
            ],

            // ===================== GOMBE STATE (state_id = 15, 11 LGA)
            15 => [
                'Akko',
                'Balanga',
                'Billiri',
                'Dukku',
                'Funakaye',
                'Gombe',
                'Kaltungo',
                'Kwami',
                'Nafada',
                'Shongom',
                'Yamaltu/Deba',
            ],

            // ===================== IMO STATE (state_id = 16, 27 LGA)
            16 => [
                'Aboh Mbaise',
                'Ahiazu Mbaise',
                'Ehime Mbano',
                'Ezinihitte',
                'Ideato North',
                'Ideato South',
                'Ihitte/Uboma',
                'Ikeduru',
                'Isiala Mbano',
                'Isu',
                'Mbaitoli',
                'Ngor Okpala',
                'Njaba',
                'Nkwerre',
                'Nwangele',
                'Obowo',
                'Oguta',
                'Ohaji/Egbema',
                'Okigwe',
                'Onuimo',
                'Orlu',
                'Orsu',
                'Oru East',
                'Oru West',
                'Owerri Municipal',
                'Owerri North',
                'Owerri West',
            ],

            // ===================== JIGAWA STATE (state_id = 17, 27 LGA)
            17 => [
                'Auyo',
                'Babura',
                'Biriniwa',
                'Birnin Kudu',
                'Buji',
                'Dutse',
                'Gagarawa',
                'Garki',
                'Gumel',
                'Guri',
                'Gwaram',
                'Gwiwa',
                'Hadejia',
                'Jahun',
                'Kafin Hausa',
                'Kazaure',
                'Kiri Kasama',
                'Kiyawa',
                'Maigatari',
                'Malam Madori',
                'Miga',
                'Ringim',
                'Roni',
                'Sule Tankarkar',
                'Taura',
                'Yankwashi',
                'Kaugama',
            ],

            // ===================== KADUNA STATE (state_id = 18, 23 LGA)
            18 => [
                'Birnin Gwari',
                'Chikun',
                'Giwa',
                'Igabi',
                'Ikara',
                'Jaba',
                'Jema\'a',
                'Kachia',
                'Kaduna North',
                'Kaduna South',
                'Kagarko',
                'Kajuru',
                'Kaura',
                'Kauru',
                'Kubau',
                'Kudan',
                'Lere',
                'Makarfi',
                'Sabon Gari',
                'Sanga',
                'Soba',
                'Zangon Kataf',
                'Zaria',
            ],

            // ===================== KANO STATE (state_id = 19, 44 LGA)
            19 => [
                'Ajingi',
                'Albasu',
                'Bagwai',
                'Bebeji',
                'Bichi',
                'Bunkure',
                'Dala',
                'Dambatta',
                'Dawakin Kudu',
                'Dawakin Tofa',
                'Doguwa',
                'Fagge',
                'Gabasawa',
                'Garko',
                'Garun Mallam',
                'Gaya',
                'Gezawa',
                'Gwale',
                'Gwarzo',
                'Kabo',
                'Kano Municipal',
                'Karaye',
                'Kibiya',
                'Kiru',
                'Kumbotso',
                'Kunchi',
                'Kura',
                'Madobi',
                'Makoda',
                'Minjibir',
                'Nasarawa',
                'Rano',
                'Rimin Gado',
                'Rogo',
                'Shanono',
                'Sumaila',
                'Takai',
                'Tarauni',
                'Tofa',
                'Tsanyawa',
                'Tudun Wada',
                'Ungogo',
                'Warawa',
                'Wudil',
            ],

            // ===================== KATSINA STATE (state_id = 20, 34 LGA)
            20 => [
                'Bakori',
                'Batagarawa',
                'Batsari',
                'Baure',
                'Bindawa',
                'Charanchi',
                'Dandume',
                'Danja',
                'Dan Musa',
                'Daura',
                'Dutsi',
                'Dutsin-Ma',
                'Faskari',
                'Funtua',
                'Ingawa',
                'Jibia',
                'Kafur',
                'Kaita',
                'Kankara',
                'Kankia',
                'Katsina',
                'Kurfi',
                'Kusada',
                'Mai\'Adua',
                'Malumfashi',
                'Mani',
                'Mashi',
                'Matazu',
                'Musawa',
                'Rimi',
                'Sabuwa',
                'Safana',
                'Sandamu',
                'Zango',
            ],

            // ===================== KEBBI STATE (state_id = 21, 21 LGA)
            21 => [
                'Aleiro',
                'Arewa Dandi',
                'Argungu',
                'Augie',
                'Bagudo',
                'Birnin Kebbi',
                'Bunza',
                'Dandi',
                'Fakai',
                'Gwandu',
                'Jega',
                'Kalgo',
                'Koko/Besse',
                'Maiyama',
                'Ngaski',
                'Sakaba',
                'Shanga',
                'Suru',
                'Wasagu/Danko',
                'Yauri',
                'Zuru',
            ],

            // ===================== KOGI STATE (state_id = 22, 21 LGA)
            22 => [
                'Adavi',
                'Ajaokuta',
                'Ankpa',
                'Bassa',
                'Dekina',
                'Ibaji',
                'Idah',
                'Igalamela-Odolu',
                'Ijumu',
                'Kabba/Bunu',
                'Kogi',
                'Lokoja',
                'Mopa-Muro',
                'Ofu',
                'Ogori/Magongo',
                'Okehi',
                'Okene',
                'Olamaboro',
                'Omala',
                'Yagba East',
                'Yagba West',
            ],

            // ===================== KWARA STATE (state_id = 23, 16 LGA)
            23 => [
                'Asa',
                'Baruten',
                'Edu',
                'Ekiti',
                'Ifelodun',
                'Ilorin East',
                'Ilorin South',
                'Ilorin West',
                'Irepodun',
                'Isin',
                'Kaiama',
                'Moro',
                'Offa',
                'Oke Ero',
                'Oyun',
                'Pategi',
            ],

            // ===================== LAGOS STATE (state_id = 24, 20 LGA)
            24 => [
                'Agege',
                'Ajeromi-Ifelodun',
                'Alimosho',
                'Amuwo-Odofin',
                'Apapa',
                'Badagry',
                'Epe',
                'Eti-Osa',
                'Ibeju-Lekki',
                'Ifako-Ijaiye',
                'Ikeja',
                'Ikorodu',
                'Kosofe',
                'Lagos Island',
                'Lagos Mainland',
                'Mushin',
                'Ojo',
                'Oshodi-Isolo',
                'Shomolu',
                'Surulere',
            ],

            // ===================== NASARAWA STATE (state_id = 25, 13 LGA)
            25 => [
                'Akwanga',
                'Awe',
                'Doma',
                'Karu',
                'Keana',
                'Keffi',
                'Kokona',
                'Lafia',
                'Nasarawa',
                'Nasarawa Eggon',
                'Obi',
                'Toto',
                'Wamba',
            ],

            // ===================== NIGER STATE (state_id = 26, 25 LGA)
            26 => [
                'Agaie',
                'Agwara',
                'Bida',
                'Borgu',
                'Bosso',
                'Chanchaga',
                'Edati',
                'Gbako',
                'Gurara',
                'Katcha',
                'Kontagora',
                'Lapai',
                'Lavun',
                'Magama',
                'Mariga',
                'Mashegu',
                'Mokwa',
                'Munya',
                'Paikoro',
                'Rafi',
                'Rijau',
                'Shiroro',
                'Suleja',
                'Tafa',
                'Wushishi',
            ],

            // ===================== OGUN STATE (state_id = 27, 20  LGA)
            27 => [
                'Abeokuta North',
                'Abeokuta South',
                'Ado-Odo/Ota',
                'Egbado North',
                'Egbado South',
                'Ewekoro',
                'Ifo',
                'Ijebu East',
                'Ijebu North',
                'Ijebu North East',
                'Ijebu Ode',
                'Ikenne',
                'Imeko Afon',
                'Ipokia',
                'Obafemi Owode',
                'Odeda',
                'Odogbolu',
                'Ogun Waterside',
                'Remo North',
                'Sagamu',
            ],

            // ===================== ONDO STATE (state_id = 28, 18 LGA)
            28 => [
                'Akoko North-East',
                'Akoko North-West',
                'Akoko South-East',
                'Akoko South-West',
                'Akure North',
                'Akure South',
                'Ese Odo',
                'Idanre',
                'Ifedore',
                'Ilaje',
                'Ile Oluji/Okeigbo',
                'Irele',
                'Odigbo',
                'Okitipupa',
                'Ondo East',
                'Ondo West',
                'Ose',
                'Owo',
            ],

            // ===================== OSUN STATE (state_id = 29, 30 LGA)
            29 => [
                'Aiyedaade',
                'Aiyedire',
                'Atakunmosa East',
                'Atakunmosa West',
                'Boluwaduro',
                'Boripe',
                'Ede North',
                'Ede South',
                'Egbedore',
                'Ejigbo',
                'Ife Central',
                'Ife East',
                'Ife North',
                'Ife South',
                'Ifedayo',
                'Ifelodun',
                'Ila',
                'Ilesa East',
                'Ilesa West',
                'Irepodun',
                'Irewole',
                'Isokan',
                'Iwo',
                'Obokun',
                'Odo Otin',
                'Ola Oluwa',
                'Olorunda',
                'Oriade',
                'Orolu',
                'Osogbo',
            ],

            // ===================== OYO STATE (state_id = 30, 33 LGA)
            30 => [
                'Afijio',
                'Akinyele',
                'Atiba',
                'Atisbo',
                'Egbeda',
                'Ibadan North',
                'Ibadan North-East',
                'Ibadan North-West',
                'Ibadan South-East',
                'Ibadan South-West',
                'Ibarapa Central',
                'Ibarapa East',
                'Ibarapa North',
                'Ido',
                'Irepo',
                'Iseyin',
                'Itesiwaju',
                'Iwajowa',
                'Kajola',
                'Lagelu',
                'Ogbomosho North',
                'Ogbomosho South',
                'Ogo Oluwa',
                'Olorunsogo',
                'Oluyole',
                'Ona Ara',
                'Orelope',
                'Ori Ire',
                'Oyo East',
                'Oyo West',
                'Saki East',
                'Saki West',
                'Surulere',
            ],

            // ===================== PLATEAU STATE (state_id = 31, 17 LGA)
            31 => [
                'Barkin Ladi',
                'Bassa',
                'Bokkos',
                'Jos East',
                'Jos North',
                'Jos South',
                'Kanam',
                'Kanke',
                'Langtang North',
                'Langtang South',
                'Mangu',
                'Mikang',
                'Pankshin',
                'Qua\'an Pan',
                'Riyom',
                'Shendam',
                'Wase',
            ],

            // ===================== RIVERS STATE (state_id = 32, 23 LGA)
            32 => [
                'Abua/Odual',
                'Ahoada East',
                'Ahoada West',
                'Akuku-Toru',
                'Andoni',
                'Asari-Toru',
                'Bonny',
                'Degema',
                'Eleme',
                'Emohua',
                'Etche',
                'Gokana',
                'Ikwerre',
                'Khana',
                'Obio/Akpor',
                'Ogba/Egbema/Ndoni',
                'Ogu/Bolo',
                'Okrika',
                'Omuma',
                'Opobo/Nkoro',
                'Oyigbo',
                'Port Harcourt',
                'Tai',
            ],

            // ===================== SOKOTO STATE (state_id = 33, 23 LGA)
            33 => [
                'Binji',
                'Bodinga',
                'Dange-Shuni',
                'Gada',
                'Goronyo',
                'Gudu',
                'Gwadabawa',
                'Illela',
                'Isa',
                'Kebbe',
                'Kware',
                'Rabah',
                'Sabon Birni',
                'Shagari',
                'Silame',
                'Sokoto North',
                'Sokoto South',
                'Tambuwal',
                'Tangaza',
                'Tureta',
                'Wamako',
                'Wurno',
                'Yabo',
            ],

            // ===================== TARABA STATE (state_id = 34, 16 LGA)
            34 => [
                'Ardo Kola',
                'Bali',
                'Donga',
                'Gashaka',
                'Gassol',
                'Ibi',
                'Jalingo',
                'Karim Lamido',
                'Kumi',
                'Lau',
                'Sardauna',
                'Takum',
                'Ussa',
                'Wukari',
                'Yorro',
                'Zing',
            ],

            // ===================== YOBE STATE (state_id = 35, 17 LGA)
            35 => [
                'Bade',
                'Bursari',
                'Damaturu',
                'Fika',
                'Fune',
                'Geidam',
                'Gujba',
                'Gulani',
                'Jakusko',
                'Karasuwa',
                'Machina',
                'Nangere',
                'Nguru',
                'Potiskum',
                'Tarmuwa',
                'Yunusari',
                'Yusufari',
            ],

            // ===================== ZAMFARA STATE (state_id = 36, 14 LGA)
            36 => [
                'Anka',
                'Bakura',
                'Birnin Magaji/Kiyaw',
                'Bukkuyum',
                'Bungudu',
                'Gummi',
                'Gusau',
                'Kaura Namoda',
                'Maradun',
                'Maru',
                'Shinkafi',
                'Talata Mafara',
                'Tsafe',
                'Zurmi',
            ],

            // ===================== FEDERAL CAPITAL TERRITORY (state_id = 37, 6 LGA)
            37 => [
                'Abaji',
                'Bwari',
                'Gwagwalada',
                'Kuje',
                'Kwali',
                'Municipal Area Council',
            ],

        ]; {
            $data = [];

            foreach ($localGovernmentAreas as $stateId => $lgas) {
                foreach ($lgas as $lga) {
                    $data[] = [
                        'state_id' => $stateId,
                        'lga_name' => $lga,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ];
                }
            }
            SetupLga::insertOrIgnore($data);
        }
    }
}
